services:
  - type: worker
    name: website-monitor
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python monitor.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9

  - type: web
    name: website-dashboard
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python dashboard.py"
    plan: free
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
